# Generated by Django 2.0.7 on 2019-05-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avg_Quality', models.CharField(max_length=32)),
                ('Real_Time_Quality', models.CharField(max_length=256)),
                ('NIR_Reading', models.IntegerField()),
            ],
        ),
    ]
