# Generated by Django 2.0.7 on 2019-05-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tank',
        ),
    ]
