# Generated by Django 2.0.7 on 2019-05-22 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190522_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality_Avg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paraffin', models.FloatField(max_length=10)),
                ('Olefins', models.FloatField(max_length=10)),
                ('Aromatics', models.FloatField(max_length=10)),
                ('tank_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Tank')),
            ],
        ),
    ]
