# Generated by Django 2.0.7 on 2019-05-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_quality_avg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quality_avg',
            name='tank_Id',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='tanksOverallStatus',
        ),
        migrations.DeleteModel(
            name='Quality_Avg',
        ),
        migrations.DeleteModel(
            name='Tank',
        ),
        migrations.DeleteModel(
            name='TanksOverallStatus',
        ),
    ]
