# Generated by Django 2.0.7 on 2019-05-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190522_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tank_No', models.IntegerField(max_length=10)),
                ('Level', models.FloatField(max_length=10)),
                ('Weight', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tanks_Overall_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='tank',
            name='tanks_Overall_Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tanks_Overall_Status'),
        ),
    ]
