# Generated by Django 2.0.7 on 2019-05-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190522_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality_avg',
            name='Colour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='FBP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='IBP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='RVP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='Sulfur',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
