# Generated by Django 2.0.7 on 2019-05-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190522_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naphtha_Load_RN', models.FloatField(max_length=10)),
                ('LPG_Load_RN', models.FloatField(max_length=10)),
                ('C5_Load_RN', models.FloatField(max_length=10)),
                ('C6_Load_RN', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Sample')),
            ],
        ),
    ]
