# Generated by Django 2.0.7 on 2019-05-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_sample_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sum',
            name='sample',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='sum',
        ),
    ]
