# Generated by Django 2.0.7 on 2019-05-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_input_parameter_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input_parameter_running',
            name='tanks_Overall_Status',
        ),
        migrations.DeleteModel(
            name='Input_Parameter_Running',
        ),
    ]
