# Generated by Django 2.0.7 on 2019-05-23 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190523_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input_Parameter_Running',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naphtha_Load_RN', models.FloatField()),
                ('LPG_Load_RN', models.FloatField()),
                ('C5_Load_RN', models.FloatField()),
                ('C6_Load_RN', models.FloatField()),
                ('Naphtha_Heater_RN', models.FloatField()),
                ('COT_RN', models.FloatField()),
                ('GF_PDI_RN', models.FloatField()),
                ('Suc_Pressure_RN', models.FloatField()),
                ('Total_Load_RN', models.FloatField(blank=True, null=True)),
                ('Paraffin_RN', models.FloatField(blank=True, null=True)),
                ('Olefins_RN', models.FloatField(blank=True, null=True)),
                ('Aromatics_RN', models.FloatField(blank=True, null=True)),
                ('Naphthene_RN', models.FloatField(blank=True, null=True)),
                ('IN_IP_Ratio_RN', models.FloatField(blank=True, null=True)),
                ('Density_RN', models.FloatField(blank=True, null=True)),
                ('IBP_RN', models.FloatField(blank=True, null=True)),
                ('FBP_RN', models.FloatField(blank=True, null=True)),
                ('tanks_Overall_Status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Tanks_Overall_Status')),
            ],
        ),
    ]
