# Generated by Django 2.0.7 on 2019-05-23 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_input_parameter_running'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input_Parameter_BestFit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Suction_Tank_No_BF', models.IntegerField()),
                ('Blending_Tank_No_BF', models.IntegerField()),
                ('Blend_Ratio_BF', models.FloatField()),
                ('Naphtha_Load_BF', models.FloatField()),
                ('LPG_Load_BF', models.FloatField()),
                ('C5_Load_BF', models.FloatField()),
                ('C6_Load_BF', models.FloatField()),
                ('Naphtha_Heater_BF', models.IntegerField()),
                ('COT_BF', models.FloatField()),
                ('GF_PDI_BF', models.FloatField()),
                ('Suc_Pressure_BF', models.FloatField()),
                ('Paraffin_BF', models.FloatField()),
                ('Olefins_BF', models.FloatField()),
                ('Aromatics_BF', models.FloatField()),
                ('Naphthene_BF', models.FloatField()),
                ('IN_IP_Ratio_BF', models.FloatField()),
                ('Density_BF', models.FloatField()),
                ('IBP_BF', models.FloatField(blank=True, null=True)),
                ('FBP_BF', models.FloatField(blank=True, null=True)),
                ('plant_Constraints', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Plant_Constraints')),
            ],
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='Aromatics',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='Olefins',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='Paraffin',
            field=models.FloatField(),
        ),
    ]
