# Generated by Django 2.0.7 on 2019-05-23 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_input_parameter_profitmax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input_Parameter_UserDefined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Suction_Tank_No_UD', models.IntegerField()),
                ('Blending_Tank_No_UD', models.IntegerField()),
                ('Blend_Ratio_UD', models.FloatField()),
                ('Naphtha_Load_UD', models.FloatField()),
                ('LPG_Load_UD', models.FloatField()),
                ('C5_Load_UD', models.FloatField()),
                ('C6_Load_UD', models.FloatField()),
                ('Naphtha_Heater_UD', models.IntegerField()),
                ('COT_UD', models.FloatField()),
                ('GF_PDI_UD', models.FloatField()),
                ('Suc_Pressure_UD', models.FloatField()),
                ('Paraffin_UD', models.FloatField()),
                ('Olefins_UD', models.FloatField()),
                ('Aromatics_UD', models.FloatField()),
                ('Naphthene_UD', models.FloatField()),
                ('IN_IP_Ratio_UD', models.FloatField()),
                ('Density_UD', models.FloatField()),
                ('IBP_UD', models.FloatField(blank=True, null=True)),
                ('FBP_UD', models.FloatField(blank=True, null=True)),
                ('quality_Real', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Quality_Real')),
            ],
        ),
        migrations.CreateModel(
            name='Output_Parameter_Running',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ethylene_RN', models.FloatField()),
                ('Propylene_RN', models.FloatField()),
                ('RPG_RN', models.FloatField()),
                ('C4_Mix_RN', models.FloatField()),
                ('Fuel_Gas_RN', models.FloatField()),
                ('Benzene_RN', models.FloatField()),
                ('BD_RN', models.FloatField()),
                ('input_Parameter_Running', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Input_Parameter_Running')),
            ],
        ),
    ]
