# Generated by Django 2.0.7 on 2019-05-23 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_input_parameter_userdefined_output_parameter_running'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output_Parameter_BestFit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ethylene_BF', models.FloatField()),
                ('Propylene_BF', models.FloatField()),
                ('RPG_BF', models.FloatField()),
                ('C4_Mix_BF', models.FloatField()),
                ('Fuel_Gas_BF', models.FloatField()),
                ('Benzene_BF', models.FloatField()),
                ('BD_BF', models.FloatField()),
                ('input_Parameter_BestFit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Input_Parameter_BestFit')),
            ],
        ),
    ]
