# Generated by Django 2.0.7 on 2019-05-23 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_output_parameter_bestfit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output_Parameter_ProfitMax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ethylene_PM', models.FloatField()),
                ('Propylene_PM', models.FloatField()),
                ('RPG_PM', models.FloatField()),
                ('C4_Mix_PM', models.FloatField()),
                ('Fuel_Gas_PM', models.FloatField()),
                ('Benzene_PM', models.FloatField()),
                ('BD_PM', models.FloatField()),
                ('input_Parameter_ProfitMax_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Input_Parameter_ProfitMax')),
            ],
        ),
    ]
