# Generated by Django 2.0.7 on 2019-05-23 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_output_parameter_profitmax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output_Parameter_UserDefined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ethylene_UD', models.FloatField()),
                ('Propylene_UD', models.FloatField()),
                ('RPG_UD', models.FloatField()),
                ('C4_Mix_UD', models.FloatField()),
                ('Fuel_Gas_UD', models.FloatField()),
                ('Benzene_UD', models.FloatField()),
                ('BD_UD', models.FloatField()),
                ('input_Parameter_UserDefined_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Input_Parameter_UserDefined')),
            ],
        ),
    ]
