# Generated by Django 2.0.7 on 2019-05-23 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_output_parameter_userdefined'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Naphtha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transport_Type', models.CharField(max_length=50)),
                ('Ship_Name', models.CharField(max_length=50)),
                ('Supplier', models.CharField(max_length=50)),
                ('Date_Transfer_From', models.DateField()),
                ('Date_Transfer_To', models.DateField()),
                ('HOJ', models.IntegerField()),
                ('Load_Port', models.CharField(max_length=50)),
                ('BL_Quantity', models.FloatField()),
                ('Shore_Quantity', models.FloatField()),
                ('Shortage_Quantity', models.FloatField()),
                ('Remaining_Stock_Calculate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='New_Naphtha_Quality_Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paraffin', models.FloatField()),
                ('Olefins', models.FloatField()),
                ('Aromatics', models.FloatField()),
                ('Naphthene', models.FloatField()),
                ('IN_IP_Ratio', models.FloatField()),
                ('Density', models.FloatField()),
                ('IBP', models.FloatField(blank=True, null=True)),
                ('FBP', models.FloatField(blank=True, null=True)),
                ('Sulfur', models.FloatField(blank=True, null=True)),
                ('Colour', models.FloatField()),
                ('RVP', models.FloatField(blank=True, null=True)),
                ('new_Naphtha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.New_Naphtha')),
            ],
        ),
        migrations.CreateModel(
            name='New_Naphtha_Quality_Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paraffin', models.FloatField(blank=True, null=True)),
                ('Olefins', models.FloatField(blank=True, null=True)),
                ('Aromatics', models.FloatField(blank=True, null=True)),
                ('Naphthene', models.FloatField(blank=True, null=True)),
                ('IN_IP_Ratio', models.FloatField(blank=True, null=True)),
                ('Density', models.FloatField(blank=True, null=True)),
                ('IBP', models.FloatField(blank=True, null=True)),
                ('FBP', models.FloatField(blank=True, null=True)),
                ('Sulfur', models.FloatField(blank=True, null=True)),
                ('Colour', models.FloatField(blank=True, null=True)),
                ('RVP', models.FloatField(blank=True, null=True)),
                ('new_Naphtha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.New_Naphtha')),
            ],
        ),
        migrations.CreateModel(
            name='New_Naphtha_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opening_Stock', models.IntegerField()),
                ('Source', models.CharField(max_length=50)),
                ('PCN_NCU', models.IntegerField()),
                ('PCN_CPP', models.IntegerField()),
                ('FGN_CPP', models.IntegerField()),
                ('CBFS_CPP', models.IntegerField()),
                ('Date', models.DateField()),
                ('Vessel_Name', models.CharField(max_length=50)),
                ('Supply_Quantity', models.IntegerField()),
                ('tanks_Overall_Status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Tanks_Overall_Status')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt_Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tank_No_1', models.FloatField(default=0)),
                ('Tank_No_2', models.FloatField(default=0)),
                ('Tank_No_3', models.FloatField(default=0)),
                ('Tank_No_4', models.FloatField(default=0)),
                ('Tank_No_5', models.FloatField(default=0)),
                ('new_Naphtha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.New_Naphtha')),
            ],
        ),
        migrations.RenameField(
            model_name='output_parameter_profitmax',
            old_name='input_Parameter_ProfitMax_Id',
            new_name='input_Parameter_ProfitMax',
        ),
        migrations.RenameField(
            model_name='output_parameter_userdefined',
            old_name='input_Parameter_UserDefined_Id',
            new_name='input_Parameter_UserDefined',
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='Colour',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='new_naphtha',
            name='new_Naphtha_Summary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.New_Naphtha_Summary'),
        ),
    ]
