# Generated by Django 2.0.7 on 2019-05-23 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20190523_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naphtha_Plan_All_Months',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month_Year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Naphtha_Plan_Single_Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Total_Stock', models.IntegerField()),
                ('Usable_Stock', models.IntegerField()),
                ('Source', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Actual_NCU_TPH', models.IntegerField()),
                ('Budget_NCU_TPH', models.IntegerField()),
                ('Actual_CPP_TPD', models.IntegerField()),
                ('Budget_CPP_TPD', models.IntegerField()),
                ('Draft_Level', models.IntegerField()),
                ('naphtha_Plan_All_Months', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Naphtha_Plan_All_Months')),
            ],
        ),
        migrations.CreateModel(
            name='Naphtha_Plan_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consumption_Total', models.FloatField(blank=True, null=True)),
                ('Consumption_NCU', models.FloatField(blank=True, null=True)),
                ('Consumption_CPP', models.FloatField(blank=True, null=True)),
                ('Procurement_Total', models.FloatField(blank=True, null=True)),
                ('Procurement_ADNOC', models.FloatField(blank=True, null=True)),
                ('Procurement_IOC', models.FloatField(blank=True, null=True)),
                ('Procurement_BPCL', models.FloatField(blank=True, null=True)),
                ('Procurement_HPCL', models.FloatField(blank=True, null=True)),
                ('Procurement_KPC', models.FloatField(blank=True, null=True)),
                ('Procurement_SPOT', models.FloatField(blank=True, null=True)),
                ('Total_Stock', models.FloatField(blank=True, null=True)),
                ('Opening_Stock', models.FloatField(blank=True, null=True)),
                ('Closing_Stock', models.FloatField(blank=True, null=True)),
                ('Avg_Stock', models.FloatField(blank=True, null=True)),
                ('Min_Stock', models.FloatField(blank=True, null=True)),
                ('Max_Stock', models.FloatField(blank=True, null=True)),
                ('naphtha_Plan_All_Months', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Naphtha_Plan_All_Months')),
            ],
        ),
    ]
