# Generated by Django 2.0.7 on 2019-05-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_new_naphtha_new_naphtha_quality_lab_new_naphtha_quality_supplier_receipt_tank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_naphtha',
            name='tanks_Overall_Status',
        ),
        migrations.RemoveField(
            model_name='new_naphtha_quality_lab',
            name='new_Naphtha',
        ),
        migrations.RemoveField(
            model_name='new_naphtha_quality_supplier',
            name='new_Naphtha',
        ),
        migrations.RemoveField(
            model_name='receipt_tank',
            name='new_Naphtha',
        ),
        migrations.DeleteModel(
            name='New_Naphtha',
        ),
        migrations.DeleteModel(
            name='New_Naphtha_Quality_Lab',
        ),
        migrations.DeleteModel(
            name='New_Naphtha_Quality_Supplier',
        ),
        migrations.DeleteModel(
            name='Receipt_Tank',
        ),
    ]
