# Generated by Django 2.0.7 on 2019-05-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_new_naphtha_new_naphtha_quality_lab_new_naphtha_quality_supplier_receipt_tank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Next_Hour_Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_D', models.BooleanField()),
                ('B_F', models.BooleanField()),
                ('P_M', models.BooleanField()),
                ('R_N', models.BooleanField()),
                ('tanks_Overall_Status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Tanks_Overall_Status')),
            ],
        ),
    ]
