# Generated by Django 2.0.7 on 2019-05-24 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_next_hour_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Output_Parameter_Running',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ethylene_RN_MO', models.FloatField()),
                ('Propylene_RN_MO', models.FloatField()),
                ('RPG_RN_MO', models.FloatField()),
                ('C4_Mix_RN_MO', models.FloatField()),
                ('Fuel_Gas_RN_MO', models.FloatField()),
                ('Benzene_RN_MO', models.FloatField()),
                ('BD_RN_MO', models.FloatField()),
                ('next_Hour_Selection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Next_Hour_Selection')),
            ],
        ),
        migrations.CreateModel(
            name='Output_Comparision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Load', models.FloatField()),
                ('Naphtha_Load', models.FloatField()),
                ('LPG_Load', models.FloatField()),
                ('C5_Load', models.FloatField()),
                ('C6_Load', models.FloatField()),
                ('Naphtha_Heater', models.IntegerField()),
                ('COT', models.FloatField()),
                ('GF_PDI', models.FloatField()),
                ('Suc_Pressure', models.FloatField()),
                ('Paraffin', models.FloatField()),
                ('Olefins', models.FloatField()),
                ('Aromatics', models.FloatField()),
                ('Naphthene', models.FloatField()),
                ('IN_IP_Ratio', models.FloatField()),
                ('Density', models.FloatField()),
                ('IBP', models.FloatField(blank=True, null=True)),
                ('FBP', models.FloatField(blank=True, null=True)),
                ('Suction_Tank_No', models.IntegerField()),
                ('Blending_Tank_No', models.IntegerField()),
                ('Blend_Ratio', models.FloatField()),
                ('Ethylene_Actual', models.FloatField()),
                ('Propylene_Actual', models.FloatField()),
                ('RPG_Actual', models.FloatField()),
                ('C4_Mix_Actual', models.FloatField()),
                ('Fuel_Gas_Actual', models.FloatField()),
                ('Benzene_Actual', models.FloatField()),
                ('BD_Actual', models.FloatField()),
                ('Ethylene_Predicted', models.FloatField()),
                ('Propylene_Predicted', models.FloatField()),
                ('RPG_Predicted', models.FloatField()),
                ('C4_Mix_Predicted', models.FloatField()),
                ('Fuel_Gas_Predicted', models.FloatField()),
                ('Benzene_Predicted', models.FloatField()),
                ('BD_Predicted', models.FloatField()),
                ('output_Parameter_Running', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Output_Parameter_Running')),
            ],
        ),
    ]
