# Generated by Django 2.2.1 on 2019-05-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_model_output_parameter_running_output_comparision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='input_parameter_bestfit',
            options={'verbose_name_plural': 'Input_Parameter_BestFit'},
        ),
        migrations.AlterModelOptions(
            name='input_parameter_profitmax',
            options={'verbose_name_plural': 'Input_Parameter_ProfitMax'},
        ),
        migrations.AlterModelOptions(
            name='input_parameter_running',
            options={'verbose_name_plural': 'Input_Parameter_Running'},
        ),
        migrations.AlterModelOptions(
            name='input_parameter_userdefined',
            options={'verbose_name_plural': 'Input_Parameter_UserDefined'},
        ),
        migrations.AlterModelOptions(
            name='login',
            options={'verbose_name_plural': 'Login'},
        ),
        migrations.AlterModelOptions(
            name='model_output_parameter_running',
            options={'verbose_name_plural': 'Model_Output_Parameter_Running'},
        ),
        migrations.AlterModelOptions(
            name='naphtha_plan_all_months',
            options={'verbose_name_plural': 'Naphtha_Plan_All_Months'},
        ),
        migrations.AlterModelOptions(
            name='naphtha_plan_single_month',
            options={'verbose_name_plural': 'Naphtha_Plan_Single_Month'},
        ),
        migrations.AlterModelOptions(
            name='naphtha_plan_summary',
            options={'verbose_name_plural': 'Naphtha_Plan_Summary'},
        ),
        migrations.AlterModelOptions(
            name='new_naphtha',
            options={'verbose_name_plural': 'New_Naphtha'},
        ),
        migrations.AlterModelOptions(
            name='new_naphtha_quality_lab',
            options={'verbose_name_plural': 'New_Naphtha_Quality_Lab'},
        ),
        migrations.AlterModelOptions(
            name='new_naphtha_quality_supplier',
            options={'verbose_name_plural': 'New_Naphtha_Quality_Supplier'},
        ),
        migrations.AlterModelOptions(
            name='next_hour_selection',
            options={'verbose_name_plural': 'Next_Hour_Selection'},
        ),
        migrations.AlterModelOptions(
            name='output_comparision',
            options={'verbose_name_plural': 'Output_Comparision'},
        ),
        migrations.AlterModelOptions(
            name='output_parameter_bestfit',
            options={'verbose_name_plural': 'Output_Parameter_BestFit'},
        ),
        migrations.AlterModelOptions(
            name='output_parameter_profitmax',
            options={'verbose_name_plural': 'Output_Parameter_ProfitMax'},
        ),
        migrations.AlterModelOptions(
            name='output_parameter_running',
            options={'verbose_name_plural': 'Output_Parameter_Running'},
        ),
        migrations.AlterModelOptions(
            name='output_parameter_userdefined',
            options={'verbose_name_plural': 'Output_Parameter_UserDefined'},
        ),
        migrations.AlterModelOptions(
            name='plant_constraints',
            options={'verbose_name_plural': 'Plant_Constraints'},
        ),
        migrations.AlterModelOptions(
            name='quality_avg',
            options={'verbose_name_plural': 'Quality_Avg'},
        ),
        migrations.AlterModelOptions(
            name='quality_nir_actual',
            options={'verbose_name_plural': 'Quality_NIR_Actual'},
        ),
        migrations.AlterModelOptions(
            name='quality_nir_pred',
            options={'verbose_name_plural': 'Quality_NIR_Pred'},
        ),
        migrations.AlterModelOptions(
            name='quality_real',
            options={'verbose_name_plural': 'Quality_Real'},
        ),
        migrations.AlterModelOptions(
            name='receipt_tank',
            options={'verbose_name_plural': 'Receipt_Tank'},
        ),
        migrations.AlterModelOptions(
            name='tank',
            options={'verbose_name_plural': 'Tank'},
        ),
        migrations.AlterModelOptions(
            name='tanks_overall_status',
            options={'verbose_name_plural': 'Tanks_Overall_Status'},
        ),
    ]
