# Generated by Django 2.2.1 on 2019-05-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20190525_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_tank',
            name='Tank_No_1_Receiving',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='receipt_tank',
            name='Tank_No_2_Receiving',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='receipt_tank',
            name='Tank_No_3_Receiving',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='receipt_tank',
            name='Tank_No_4_Receiving',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='receipt_tank',
            name='Tank_No_5_Receiving',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='input_parameter_userdefined',
            name='Aromatics_UD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='input_parameter_userdefined',
            name='Density_UD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='input_parameter_userdefined',
            name='IN_IP_Ratio_UD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='input_parameter_userdefined',
            name='Naphthene_UD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='input_parameter_userdefined',
            name='Olefins_UD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='input_parameter_userdefined',
            name='Paraffin_UD',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
