# Generated by Django 2.2.1 on 2019-05-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20190526_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='Receiving_Naphtha',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
