# Generated by Django 2.0.7 on 2019-05-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_tank_receiving_naphtha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_naphtha_quality_lab',
            name='FBP',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='new_naphtha_quality_lab',
            name='IBP',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='new_naphtha_quality_lab',
            name='RVP',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='new_naphtha_quality_lab',
            name='Sulfur',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='FBP',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='IBP',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='RVP',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='Sulfur',
            field=models.FloatField(default=0),
        ),
    ]
