# Generated by Django 2.0.7 on 2019-05-27 11:51

from django.db import migrations, models
import djangoapp.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20190527_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality_avg',
            name='Aromatics',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='Colour',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='Density',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='FBP',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='IBP',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='IN_IP_Ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='Naphthene',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='Olefins',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='Paraffin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='RVP',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quality_avg',
            name='Sulfur',
            field=models.FloatField(default=0),
        ),
    ]
