# Generated by Django 2.0.7 on 2019-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20190527_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='Weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
