# Generated by Django 2.0.7 on 2019-05-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20190528_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanks_overall_status',
            name='Blend_Ratio_RN',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tanks_overall_status',
            name='Blending_Tank_No_RN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tanks_overall_status',
            name='Suction_Tank_No_RN',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
