# Generated by Django 2.0.7 on 2019-05-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20190528_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_parameter_userdefined',
            name='quality_Real',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tanks_Overall_Status'),
        ),
    ]
