# Generated by Django 2.0.7 on 2019-05-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20190528_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input_parameter_userdefined',
            name='quality_Real',
        ),
        migrations.RemoveField(
            model_name='output_parameter_userdefined',
            name='input_Parameter_UserDefined',
        ),
        migrations.DeleteModel(
            name='Input_Parameter_UserDefined',
        ),
        migrations.DeleteModel(
            name='Output_Parameter_UserDefined',
        ),
    ]
