# Generated by Django 2.0.7 on 2019-05-28 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20190528_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input_Parameter_UserDefined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Suction_Tank_No_UD', models.IntegerField()),
                ('Blending_Tank_No_UD', models.IntegerField()),
                ('Blend_Ratio_UD', models.FloatField()),
                ('Naphtha_Load_UD', models.FloatField()),
                ('LPG_Load_UD', models.FloatField()),
                ('C5_Load_UD', models.FloatField()),
                ('C6_Load_UD', models.FloatField()),
                ('Naphtha_Heater_UD', models.IntegerField()),
                ('COT_UD', models.FloatField()),
                ('GF_PDI_UD', models.FloatField()),
                ('Suc_Pressure_UD', models.FloatField()),
                ('Paraffin_UD', models.FloatField(blank=True, null=True)),
                ('Olefins_UD', models.FloatField(blank=True, null=True)),
                ('Aromatics_UD', models.FloatField(blank=True, null=True)),
                ('Naphthene_UD', models.FloatField(blank=True, null=True)),
                ('IN_IP_Ratio_UD', models.FloatField(blank=True, null=True)),
                ('Density_UD', models.FloatField(blank=True, null=True)),
                ('IBP_UD', models.FloatField(blank=True, null=True)),
                ('FBP_UD', models.FloatField(blank=True, null=True)),
                ('quality_Real', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Quality_Real')),
            ],
            options={
                'verbose_name_plural': 'Input_Parameter_UserDefined',
            },
        ),
        migrations.CreateModel(
            name='Output_Parameter_UserDefined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ethylene_UD', models.FloatField()),
                ('Propylene_UD', models.FloatField()),
                ('RPG_UD', models.FloatField()),
                ('C4_Mix_UD', models.FloatField()),
                ('Fuel_Gas_UD', models.FloatField()),
                ('Benzene_UD', models.FloatField()),
                ('BD_UD', models.FloatField()),
                ('input_Parameter_UserDefined', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Input_Parameter_UserDefined')),
            ],
            options={
                'verbose_name_plural': 'Output_Parameter_UserDefined',
            },
        ),
    ]
