# Generated by Django 2.0.7 on 2019-05-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_input_parameter_userdefined_output_parameter_userdefined'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='test',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
