# Generated by Django 2.0.7 on 2019-05-29 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20190529_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='input_parameter_userdefined',
            name='Confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='input_parameter_userdefined',
            name='tanks_Overall_Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Tanks_Overall_Status'),
        ),
    ]
