# Generated by Django 2.0.7 on 2019-05-30 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20190530_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naphtha_plan_single_month',
            name='naphtha_Plan_All_Months',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Naphtha_Plan_All_Months'),
        ),
    ]
